spring:
  application:
    name: Integratez Platform

  profiles:
    active: dev  # default active profile (change to prod/test as needed)
    group:
      dev: "dev"
      test: "test"
      prod: "prod"

  config:
    import:
      - classpath:config/application-dev.yaml
      - classpath:config/application-test.yaml
      - classpath:config/application-prod.yaml

# Common JPA Configurations (apply to all profiles)
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true

cloud:
  compatibility-verifier:
    enabled: false

shopify:
client-id: 95309d3d3af210ada84f2ef2c31e51cf
client-secret: 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
scopes: read_orders,write_orders,read_products,write_products,read_fulfillments,write_fulfillments
redirect-uri: https://casimira-inductile-affectedly.ngrok-free.dev/shopify/callback
access-mode: online
api-version: 2025-10 # keep current
app-url: https://casimira-inductile-affectedly.ngrok-free.dev


