spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/integratez
    username: root
    password: Jsk1950@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

logging:
  level:
    root: INFO
    com.integratez: DEBUG

mail:
  host: smtp.gmail.com
  port: 587
  username: jayy15536@gmail.com
  password: skpq vwsh cpex jxbo
  properties:
    mail:
      baseurl: https://casimira-inductile-affectedly.ngrok-free.dev
      smtp:
        auth: true
        starttls:
          enable: true

shopify:
api-key: 95309d3d3af210ada84f2ef2c31e51cf
api-secret: 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
scopes: read_orders,write_orders,read_products,write_products,read_fulfillments,write_fulfillments
redirect-uri: https://casimira-inductile-affectedly.ngrok-free.dev/shopify/callback
access-mode: online
api-version: 2025-10 # keep current
app-url: https://casimira-inductile-affectedly.ngrok-free.dev





